name: Update daily.dev DevCard

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  update-devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update daily.dev DevCard
        uses: dailydotdev/action-devcard@3.2.1
        with:
          user_id: ${{ secrets.USER_ID }}
          # type puede ser "default" (vertical) o "wide"
          type: default
          # nombre del archivo a guardar
          commit_filename: devcard.png
          commit_message: "chore: update devcard [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
